<?php

namespace Mapal\GEPBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Mapal\GEPBundle\Entity\Status;

/**
 * StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusRepository extends EntityRepository{
	
	/**
	 * Get the default status
	 *
	 * @return Status
	 */
	public function findDefaultStatus( ){
	
		$status = null;
	
		try{
	
			$result = $this->getEntityManager()->createQuery(
					"SELECT s ".
					"FROM MapalGEPBundle:".Status::$ENTITY_NAME." s ".
					"WHERE s.".Status::$FIELD_NAME_DETAULT." = :isDefaultStatus "
			)
			->setParameter('isDefaultStatus', 1)
			->getResult();
	
			$status = $result[0];
	
		}catch ( Exeption $e ){
	
		}
			
		return $status;
	
	}
	
}
