<?php

namespace Mapal\GEPBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Mapal\GEPBundle\Entity\SystemParam;

/**
 * StatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemParamRepository extends EntityRepository{
	
	public function saveOrUpdate(SystemParam $systemParam){
	
		$em = $this->getEntityManager();
	
		if ($systemParam->getId()>0){
	
			$loadSystemParam = $em->getRepository('MapalGEPBundle:SystemParam')->find($systemParam->getId());
				
			$loadSystemParam->setKey($systemParam->getkey());
			$loadSystemParam->setValue($systemParam->getValue());
				
		}else{
				
			$em->persist($systemParam);
				
		}
	
		$em->flush();
	
		return $systemParam->getId();
	
	}
	
	public function remove(SystemParam $systemParam){
	
		$em = $this->getEntityManager();
		$entity = $em->merge($systemParam);
		$em->remove($entity);
		$em->flush();
	
	}
	
	/**
	 * Get the value for a key
	 *
	 * @return Status
	 */
	public function findByKey( $key ){
	
		$systemParam = null;
	
		try{
	
			$result = $this->getEntityManager()->createQuery(
					"SELECT sp ".
					"FROM MapalGEPBundle:".SystemParam::$ENTITY_NAME." sp ".
					"WHERE sp.".SystemParam::$FIELD_NAME_KEY." = :key "
			)
			->setParameter('key', $key)
			->getResult();
	
			if ( count($result) ){
				$systemParam = $result[0];
			}
	
		}catch ( Exeption $e ){
	
		}
			
		return $systemParam;
	
	}
	
}
