<?php

namespace Mapal\GEPBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Mapal\GEPBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository{
	
	public function saveOrUpdate(User $user){
	
		$em = $this->getEntityManager();
		
		if ($user->getId()>0){
		
			$loadUser = $em->getRepository('MapalGEPBundle:User')->find($user->getId());
			
			$loadUser->setUser($user->getUser());
			$loadUser->setPass($user->getPass());
			$loadUser->setName($user->getName());
			$loadUser->setEmail($user->getEmail());
			$loadUser->setIsAdmin($user->getIsAdmin());
			
		}else{
			
			$em->persist($user);
			
		}
		
		$em->flush();
		
		return $user->getId();

	}
	
	public function remove(User $user){
	
		$em = $this->getEntityManager();
		$entity = $em->merge($user);
		$em->remove($entity);
		$em->flush();
	
	}
	
	public function getUserByUserAndPass($user,$pass){
		
		$entity = null;
		
		try{
		
			$result = $this->getEntityManager()->createQuery(
					"SELECT u ".
					"FROM MapalGEPBundle:".User::$ENTITY_NAME." u ".
					"WHERE u.".User::$FIELD_NAME_USER." = :user ".
					"AND u.".User::$FIELD_NAME_PASS." = :pass "
			)
			->setParameter('user', $user)
			->setParameter('pass', md5($pass))
			->getResult();
		
			if ( count($result) ){
				$entity = $result[0];
			}
		
		}catch ( Exeption $e ){
		
		}
			
		return $entity;
		
	}
	
}
