<?php

namespace Mapal\GEPBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Mapal\GEPBundle\Entity\Week;

/**
 * WeekRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeekRepository extends EntityRepository{
	
	public function saveOrUpdate(Week $week){
	
		$em = $this->getEntityManager();
		$em->persist($week);
		$em->flush();
	
	}
	
	/**
	 * Get the list of week of a year
	 * @param year
	 * @return List<Week>
	 */
	public function findAllWithYear( $year ){
	
		$lstWeek = array();
	
		try{
	
			$result = $this->getEntityManager()->createQuery(
					"SELECT w ".
					"FROM MapalGEPBundle:".Week::$ENTITY_NAME." w ".
					"WHERE w.".Week::$FIELD_NAME_YEAR." = :year ".
					"ORDER BY  w.".Week::$FIELD_NAME_WEEK." ASC "
			)
			->setParameter('year', $year)
			->getResult();
	
			$lstWeek = $result;
	
		}catch ( Exeption $e ){
	
		}
			
		return $lstWeek;
	
	}
	
}